name: taiga_rest_models
description: Taiga rest models
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
dependencies:
  crypto: ^3.0.3
  dart_mappable: ^4.0.1
  freezed_annotation: ^2.4.1
  http: ^0.13.3
  json_annotation: ^4.8.1
