name: taiga_consumer_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_mappable: ^4.0.1
  serverpod: 1.2.2
  taiga_rest_models:
    git:
      url: https://github.com/Eficetti/taigaREST_models.git
  gitlab_rest_models:
    git:
      url: https://github.com/N-KILL/gitlabREST_models.git
  communication_service:
    git:
      url: https://github.com/Rodsevich/communications-service.git
      ref: postgres-2.6.1
  cron: ^0.6.0

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
