name: gitlab_rest_models
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.6
  dart_mappable_builder: ^4.0.1
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
  
dependencies:
  dart_mappable: ^4.0.1
  http: ^0.13.6
  logger: ^2.0.2+1
  
